/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE productBaseService PLEASE EDIT ../product.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Product } from '../../domain/angulartest_db/product';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../product.service.ts
 */

/*
 * SCHEMA DB product
 *
	{
		product_id: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		product_id: [{
			type: Schema.ObjectId,
			ref : "price"
		}],
	}
 *
 */
@Injectable()
export class ProductBaseService {

    private productCollection: AngularFirestoreCollection<Product>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.productCollection = afs.collection<Product>('product');
    }


    // CRUD METHODS

    /**
    * productService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.productCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * productService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Product[]> {
        return this.afs.collection('product').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Product;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }


    // Custom APIs

}
